export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_PRODUCTS_BY_CATEGORY: "FETCH_PRODUCTS_BY_CATEGORY",
  FETCH_PRODUCTS_BY_ID: "FETCH_PRODUCTS_BY_ID",
};
